### PR TITLE
UI Enhancement and Feature Update

### PR DESCRIPTION
**Pull request by Zingzy**
## Changelog

- Enhanced UI responsiveness by implementing `threading`.
- Modernized and unified the UI design for a consistent user experience.
- Included Stars Count and Author Image in the Package Info window.
- Added click to copy for the package install input box.
- Added a contribution link to the About window.
- Implemented logic to center TopLevel Windows.
- Updated the UI font to "Segoe UI" for better readability.
- Adjusted spacing for a cleaner and more consistent appearance.
- Added `.gitignore` and `requirements.txt`

## Changes Previews

Main Window

About Window

Package Info Window

https://github.com/Akascape/tkinter-toolkit/assets/90309290/a01c00de-4299-4ba7-8b54-65865f7fe347

P.S : I also updated the database information of my package `hPyT` and I also used this package in this project to simplify certain things, hope that it is not a problem

### CODE REVIEW

**Comment by Akascape** [comment]
@Zingzy You added hpyt but it will not work in other OS except windows. For now, we can remove the center relative feature from this app.

**Comment by Akascape** [comment]
Seconly, instead of using pyperclip we can use tkinter's `self.clipboard_append` method to copy things.

**Comment by Akascape** [comment]
@Zingzy I will modify this fork later,

**Comment by Zingzy** [comment]
No worries, if you want I can make these changes and update the pull request

**Comment by Akascape** [comment]
@Zingzy I have already made the changes

**Pull request merged**
