### PR TITLE
Add `ttkthemes` and `ttkwidgets`

### PR DESCRIPTION
**Pull request by rdbende**

### CODE REVIEW

**Review by Akascape — APPROVED** [review]

**Comment by Akascape** [comment]
@rdbende Can you please add one image of the libraries? Just upload it here on comments directly.

**Comment by rdbende** [comment]
ttkhemes_cover

**Comment by Akascape** [comment]
@rdbende This one is for ttkthemes right? One for ttkwidgets?

**Comment by Akascape** [comment]
@rdbende I tested some ttkwidgets, they are really great, especially the timeline widget is so unique.

Screenshot

This one look better i guess. It can also be uploaded to the ttkwidget repository if possible,

**Comment by rdbende** [comment]
Yeah, your screenshot showcases the widgets far better :))

**Pull request merged**
