### PR TITLE
Update database.json

### PR DESCRIPTION
**Pull request by Thisal-D**
Nativesvttk

Pypi : [Nativesvttk](https://pypi.org/project/nativesvttk/)

### CODE REVIEW

**Comment by Akascape** [comment]
@Thisal-D 
This project has nothing new, I checked all the code,
- No proper documentation, github repo
- Just like the sv-ttk theme, (nothing new)
- Titlebar color changing to dark/light, just like we have in customtkinter or pywinstyles
- It has messagebox which simply uses my CTkMessagebox library, nothing custom-made.
- No other special functionality or widgets

As mentioned here https://github.com/Akascape/tkinter-toolkit/discussions/1, there should be some minimum requirements for a project.

**Comment by jhi2** [comment]
> * Titlebar color changing to dark/light, just like we have in customtkinter or pywinstyles

What is CustomTkinter?

**Comment by Akascape** [comment]
@jhi2 See here: https://github.com/TomSchimansky/CustomTkinter

**Comment by jhi2** [comment]
Yes

**Comment by jhi2** [comment]
I am also working on a not-tk gui toolkit, powerd by winUI3(Windows 10 and 11 only)

**Pull request closed without merging**
